name: @name@
version: @version@
author: bei2
main: com.gmx.mattcha.sit.MainClass
api-version: 1.14

commands:
  sit:
    description: You can sit down
    usage: /sit
    permission: sit.command.sit

permissions:
  sit:
    children:
      sit.command:
        children:
          sit.command.sit:
            description: Allow a player to sit
            default: true
